services:
  mariadb:
    build: ./requirements/mariadb
    expose:
      - "3306" # pierre dit qu'il faut pas car ils sont deja sur le meme network
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - app-network
    container_name: "mariadb"
    env_file:
      - ./.env
  wordpress:
    build: ./requirements/wordpress
    expose:
      - "9000" # pierre dit qu'il faut pas car ils sont deja sur le meme network
    volumes:
      - wpdata:/var/www/html
    networks:
      - app-network
    container_name: "wordpress"
    depends_on:
      - mariadb
    env_file:
      - ./.env
  nginx:
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wpdata:/var/www/html
    networks:
      - app-network
    depends_on:
      - wordpress
    container_name: "nginx"

volumes:
  dbdata:
    driver: local
    name: dbdata
    driver_opts:
      device: /home/mniemaz/data/mariadb
      type: "none"
      o: bind
  wpdata:
    driver: local
    name: wpdata
    driver_opts:
      device: /home/mniemaz/data/wordpress
      type: "none"
      o: bind

networks:
  app-network:
    driver: bridge